### ISSUE TITLE
Minor bug in https://github.com/health-data-science-OR/stochastic_systems/blob/master/labs/simulation/lab1/simulation_lab1_SOLUTIONS.ipynb

### ISSUE THREAD

**Issue by ploginovic** [health-data-science-OR/stochastic_systems#6]
Function 'print_patient_details(acute, home)' in simulation/lab1/simulation_lab1/simulationation_lab1_*.ipynb has hardcoded dataframe names instead of function parameters. It's the same in both STUDENT and SOLUTION notebooks. Line 6 should be

df = pd.DataFrame(np.vstack([acute, home])).T

**Comment by TomMonks** [comment]
fixed in upcoming 2025 release. Thank you!
